{% set name = "aws-embedded-metrics" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-embedded-metrics-{{ version }}.tar.gz
  sha256: f417c396b394959f923d5b53cfe241d01a0ccded60c8f30d9231ff05c8235ec5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - aiohttp

test:
  imports:
    - aws_embedded_metrics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awslabs/aws-embedded-metrics-python
  summary: AWS Embedded Metrics Package
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - zuoyuan-alt
    - seoberha
    - zuoyuanh
